import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineWhatsApp,
} from "react-icons/ai";
import FloatingWhatsApp from "../components/FloatingWhatsApp/FloatingWhatsApp";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pedro Aznarez Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developedbypeter</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <FloatingWhatsApp />
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Pedro Aznarez
            </h2>
            <h3 className="text-2xl py-2">Developer and Designer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Hi, I'm Pedro, Frontend Developer. Passionate about designing
              beautiful web interfaces. Based in Uruguay.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiOutlineWhatsApp />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Creating responsive and interactive websites, portafolios,
              e-commerce, using{" "}
              <span
                className="text-teal-500 font-bold
              "
              >
                React, HTML5, CSS3, Javascript, Bootstrap{" "}
              </span>{" "}
              and other technologies.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Creating responsive and interactive websites, portafolios,
              e-commerce, using{" "}
              <span
                className="text-teal-500 font-bold
              "
              >
                React, HTML5, CSS3, Javascript, Bootstrap{" "}
              </span>{" "}
              and other technologies.
            </p>
          </div>
          <div>
            <div>
              <Image src={design} width={100} height={100} />
              <h3>Beautiful Designs</h3>
              <p>Creating Designs</p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">React</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
